name: Release

# https://docs.github.com/en/actions/writing-workflows/choosing-when-your-workflow-runs/events-that-trigger-workflows#release
# https://github.com/marketplace/actions/goreleaser-action#run-on-new-tag
on:
  release:
    types: [published]

permissions:
  contents: write # GoReleaser
  packages: write # Docker
  actions: read # Syft
  # Attestation
  id-token: write
  attestations: write
  artifact-metadata: write

jobs:
  publish-release:
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v6 # https://github.com/marketplace/actions/checkout
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v6 # https://github.com/marketplace/actions/setup-go-environment
        with:
          go-version-file: go.mod

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v7 # https://github.com/marketplace/actions/goreleaser-action
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Generate attestation for archives
        uses: actions/attest-build-provenance@v3 # https://github.com/marketplace/actions/attest-build-provenance
        with:
          subject-checksums: ./dist/revchat_${{ github.ref_name }}_checksums.txt

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3 # https://github.com/marketplace/actions/docker-login
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3 # https://github.com/marketplace/actions/docker-setup-qemu
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3 # https://github.com/marketplace/actions/docker-setup-buildx
      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5 # https://github.com/marketplace/actions/docker-metadata-action
        with:
          images: ghcr.io/${{ github.repository }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6 # https://github.com/marketplace/actions/build-and-push-docker-images
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          push: true
          sbom: false
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Generate attestation for Docker image
        uses: actions/attest-build-provenance@v3
        with:
          subject-name: ghcr.io/${{ github.repository }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true

      - name: Generate SBOM
        uses: anchore/sbom-action@v0 # https://github.com/marketplace/actions/anchore-sbom-action
        with:
          image: ghcr.io/${{ github.repository }}:${{ github.ref_name }}
          dependency-snapshot: true
